### ISSUE TITLE
Add a tag similar to discord-attachments but for "autplayed looped no-control" videos

### ISSUE THREAD

**Issue by DarkGuy10** [skyra-project/discord-components#126]
The idea is to play tenor gifs in video format, like the original client:
![image](https://user-images.githubusercontent.com/62807269/132665102-df8d99a9-1fd1-4319-b9af-efe8ec7e7ce3.png)
The styling is almost similar to message attachments.

[Link to above gif](https://tenor.com/view/haikyuu-kageyama-shout-disguise-yell-gif-4916447)

**Comment by Favna** [comment]
<img src="https://c.tenor.com/Qeom_gC-4XYAAAAC/haikyuu-kageyama.gif" />

```
<img src="https://c.tenor.com/Qeom_gC-4XYAAAAC/haikyuu-kageyama.gif" />
```

Just get the actual gif URL and add it in an image tag in the current attachment component

**Comment by DarkGuy10** [comment]
Yh but the link comes as the `video` property of a `MessageEmbed`

**Comment by DarkGuy10** [comment]
I added the tag in my fork, its working fine now :)
