### ISSUE TITLE
request: Custom emoji component for messages and embeds

### ISSUE THREAD

**Issue by acupoftee** [skyra-project/discord-components#163]
What are your thoughts on a `Discord-Emoji` component allowing developers to add custom server emojis to their messages? 

This component could accept an `emojiName` and `emojiUrl` as properties. They would also be inline components which would be embedded in messages or text. Bot developers using custom emojis in their bots would definitely benefit from this feature. 

For bot developers using custom emojis in their embed titles, what are your thoughts on including the ability to add custom emojis in embed titles and field names like so? 

### Discord Custom Emoji Examples
<img width="379" alt="Screen Shot 2021-11-06 at 7 37 35 PM" src="https://user-images.githubusercontent.com/15068267/140626986-b3e3c9c8-3ff0-477e-b542-3f86d588888b.png">
<img width="499" alt="Screen Shot 2021-11-06 at 7 42 46 PM" src="https://user-images.githubusercontent.com/15068267/140627027-b2c09bd2-ebe1-4bbf-a25c-e15d0e9f1ade.png">

I'd be more than happy to help implement this if needed!

**Comment by favna** [comment]
I think it would be really interesting. Of course it's technically already possible by inlining an `<img src="" alt="" />` tag, but `Discord-Custom-Emoji` (note: I changed the name here, to make it clear it's not a Twemoji) could set the proper width and height.

**Comment by acupoftee** [comment]
> I think it would be really interesting. Of course it's technically already possible by inlining an <img src="" alt="" /> tag, but <discord-custom-emoji> (note: I changed the name here, to make it clear it's not a Twemoji) could set the proper width and height.

Definitely. In messages, they're 22x22 pixels, and 18x18 pixels in embeds. 

I started experimenting with the possibility of adding custom emojis to embed titles and field names too since I wasn't able to to change the titles with Vue and React on runtime.

 I added an `Emoji` interface with `name` and `url` properties. Then I added an `emojis` prop to `DiscordMessageOptions` for developers to register custom emojis. This way if there was a way to parse them, we could grab the custom emoji information and replace the emoji text with the custom component. 

#### Embed with custom emojis in titles
```diff
<discord-embed
	slot="embeds"
	author-image="/static/sapphire.png"
+	author-name=":custom_emoji: Sapphire Developers"
	author-url="https://sapphirejs.dev"
	color="#0F52BA"
+	embed-title=":custom_emoji: Sapphire"
>

	<discord-embed-fields slot="fields">
+		<discord-embed-field field-title=":computer_emoji: Installation"> yarn add @sapphire/framework </discord-embed-field>
+		<discord-embed-field field-title=":key_emoji: Key Features">
			...
		</discord-embed-field>
	</discord-embed-fields>
</discord-embed>
```

#### Example emoji config
```js
window.$discordMessage = {
	emojis: {
		custom_emoji: {
			name: "custom_emoji",
			url: "https://cdn.discordapp.com/emojis/742580958527619112.png"
		},
	}
};
```

> As for twemojis, we can create <discord-twemoji> which takes an argument of twemojiName which references a Map<string, string> filled with the twemoji names as they are known on Discord as keys and their respective codes as values, for example https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72/2b07.png is arrow_down: Filling that map will be a huge chore though... there's so many. Make sure to make it its own file. twemojiName should be an optional property, and another optional property should be encodedTwemoji because %E2%AC%87%EF%B8%8F will resolve to the same arrow down emoji. We can make a runtime check that one of the two is provided.

Sounds like a plan. Yup, definitely are a lot of them for sure, but a straight forward plan 👍

**Comment by favna** [comment]
Code above LGTM. Will you make a PR?

**Comment by acupoftee** [comment]
Thank you, and yup!

**Comment by YoannMa** [comment]
You don't need to create a mapping for the Twemoji as you can build the code from the name, I took the algorithm from https://github.com/twitter/twemoji and made my own helper to get the URL out of an emoji object

```javascript

    /**
     * @param {Emoji|GuildEmoji|ReactionEmoji} emoji
     * @param {Object}                         [options]
     *
     * @return {string}
     */
    static emojiURL(emoji, options = {}) {

        if (emoji.url) {

            return emoji.url;
        }

        const { cdn = 'https://twemoji.maxcdn.com', v = 'latest', sep = '-', size = '72x72', ext = 'png' } = options;

        const surrogates = emoji.name.indexOf(String.fromCharCode(0x200D)) < 0 ? emoji.name.replace(/\uFE0F/g, '') : emoji.name;

        const r = [];

        let c = 0;
        let p = 0;
        let i = 0;

        while (i < surrogates.length) {

            c = surrogates.charCodeAt(i++);

            if (p) {
                r.push((0x10000 + ((p - 0xD800) << 10) + (c - 0xDC00)).toString(16));
                p = 0;
            }
            else if (c >= 0xD800 && c <= 0xDBFF) {
                p = c;
            }
            else {
                r.push(c.toString(16));
            }
        }

        const code = r.join(sep);

        return [cdn, 'v', v, size, `${ code }.${ ext }`].join('/');
    }

```

I haven't tested all the different Twemoji, but I tested composed emoji like `:woman_factory_worker:` without issues.

**Comment by favna** [comment]
That's very interesting @YoannMa. I never would've thought it could be done like that. Thanks!
