### ISSUE TITLE
request: building a single file version

### ISSUE THREAD

**Issue by YoannMa** [skyra-project/discord-components#172]
**Is your feature request related to a problem? Please describe.**

I'm building a screenshot feature on my Bot, using this package, building the webpage with Pug and rendering with Puppeteer, sadly I cannot import the package directly into the Puppeteer webpage, I can only make it work with the unpkg URL.

I can use the `addScriptTag` feature of Puppeteer, but relative import in the script won't work https://devdocs.io/puppeteer/index#pageaddscripttagoptions

Using unpkg is fine, but I rather not depend on them, especially when I can have the package locally, avoiding the extra 1-5 requests

**Describe the solution you'd like**

I was wondering if you could build a single file version of the package (minified or not) ? 

**Describe alternatives you've considered**

**Additional context**

Using `@skyra/discord-components-core` package

**Comment by favna** [comment]
Sorry but no can do. It's not something StencilJS supports: https://stenciljs.com/docs/distribution

An alternative solution to using unpkg and when using Sapphire framework is using our [@sapphire/plugin-api](https://www.sapphirejs.dev/docs/Guide/plugins/API/getting-started) and providing the proper JS file that way.

**Comment by YoannMa** [comment]
Alright, make sense, thanks for the idea of exposing the pacakge through a webserver
