### ISSUE TITLE
request: Select menu for message !

### ISSUE THREAD

**Issue by exatombe** [skyra-project/discord-components#185]
**Component request to add**

Can you add Select menu component ?
This component work same as a button (because it's a component), but it took Five place (you can't place buttons and select menu at the same Row)
You can only place one select menu by row ^^

Thx if you can add it
<img width="316" alt="image" src="https://user-images.githubusercontent.com/65552225/147303775-b065421c-a5e3-44ea-a331-b5f484419663.png">
<img width="357" alt="image" src="https://user-images.githubusercontent.com/65552225/147303818-d8259ef0-afa4-4a14-9674-9ddbff0171c5.png">

**Comment by Nzii3** [comment]
This would be cool. Maybe optional values that are already selected? Like this: 
![IMG_4742](https://github.com/skyra-project/discord-components/assets/106406461/55e139ff-c888-4f9c-90da-323588f01921)

**Comment by favna** [comment]
Released string select menu in [v4.0.0-alpha.25](https://github.com/skyra-project/discord-components/releases/tag/v4.0.0-alpha.25)
