### ISSUE TITLE
request: Support embed description styles

### ISSUE THREAD

**Issue by sunlanterns** [skyra-project/discord-components#193]
**Is your feature request related to a problem? Please describe.**

Support using `<strong>`, `<code>`, `<em>`, etc and style them the same way that discord styles the similar markdown syntaxes: `**`, `\``, `*`

I'm currently using this package in combination with this package:
https://github.com/brussell98/discord-markdown

To take valid markdown (that would be used by my bot in discord in the long run) and translate it to valid HTML inside of the `discord-embed-description` component to preview it in the page.

**Describe the solution you'd like**

Just some in-built css styling for those elements inside of `discord-embed-description`'s styles!

**Describe alternatives you've considered**

I can style it myself, and I might do that in the short term but it would be nice if it was just included as a part of this package.

**Comment by favna** [comment]
I honestly don't think this should be something this library does. There is also already the perfect library [marked](https://www.npmjs.com/package/marked) which does markdown to HTML. Between that and discord-markdown, there are plenty of options to convert markdown to HTML. For the library to do this we would need to make a token parser just to convert something like `this is **bold** and *italic* and **more bold**` to 
```html
<span>this is<strong>bold</strong> and <em>italic</em> and <strong>more bold</strong></span>
```

Not to mention that the common practice is not to use `strong` and `em` as opposed to CSS for styling anyway (HTML should not be responsible for styling and different browsers and operating systems may react differently to strong and em).

And now I've only covered bold and italic. Lets consider something like code, `inline code blocks` are easy enough, but for multi-line code blocks we would need the library to pull in HighlightJS which bulks up the package by a lot, and maybe someone would rather want to use PrismJS or something else.

**Comment by sunlanterns** [comment]
I feel like I may have miss communicated!

I was not asking that this library support translating the markdown to html. But that if the html tags are already present as content in `discord-embed-description`, then they would be styled to match discords own styling. If that's still something you'd rather not support, I'd understand, I just wanted to make sure I was clear. 

> Not to mention that the common practice is not to use strong and em 

I'm a professional web developer - specifically I specialize in creating design system components. And even though it may be *common*, it's not considered *good*. It's considered better practice to use semantic tags where possible and apply custom styling to them to be able to support accessibility more naturally. Discord itself, when I inspected their code earlier to see, uses the strong tag to do bolding.

**Comment by favna** [comment]
Oh I guess I also misunderstood. Well.. would you be willing to make a PR for it? I think it's pretty straightforward, it's one CSS file and the basic idea is just `.discord-embed-description strong`, but I'm sure you know how CSS element targeting works.

**Comment by sunlanterns** [comment]
Sure!
Might be another couple of days before I get to it just because I did a very quick job of it on my first run through, and I'd rather do it right before committing it to a library, haha.

**Comment by sunlanterns** [comment]
I said a couple of days and then I ended up turning around and getting it done immediately anyway:
https://github.com/skyra-project/discord-components/pull/195

**Comment by favna** [comment]
> I said a couple of days and then I ended up turning around and getting it done immediately anyway: #195

been there done that lol
