### ISSUE TITLE
bug: multiline messages are rendered in same line

### ISSUE THREAD

**Issue by DarkGuy10** [skyra-project/discord-components#201]
**Describe the bug**
Multiline messages get rendered in the same line

**Expected behavior**
![image](https://user-images.githubusercontent.com/62807269/152142107-0e4c7c11-deb2-4fd2-9dd8-1e154bbdbab6.png)

**Actual behaviour**
![image](https://user-images.githubusercontent.com/62807269/152142187-c1a8fc78-87f6-4c67-9f15-940a6382ab29.png)

**Additional context**
Easy fix, add `white-space: pre;` to the `.discord-message-markup` class.

**Comment by favna** [comment]
I'm sorry but this is not a bug. Multilines are supposed to be rendered as 1 line in HTML. For example, take this code sample:
https://github.com/skyra-project/discord-components/blob/c95dd81b03c042e695dd21db3c62c7137a4426f1/packages/core/src/index.html#L100-L105

This is rendered like:
![image](https://user-images.githubusercontent.com/4019718/152215965-7bfe2ddf-2d9f-4e50-88f1-e554a9ae65c6.png)

However with your change that becomes:
![image](https://user-images.githubusercontent.com/4019718/152215996-fabeea39-cc7a-43ca-a9be-54dcba250e78.png)

The only way your CSS change would then make the HTML code render the same would be to write it like:
```html
<discord-message profile="maximillian">Hey, <discord-mention>Alyx Vargas</discord-mention> and <discord-mention>Dawn</discord-mention>. Welcome to our server!<br />Be sure to read through the <discord-mention type="channel">rules</discord-mention>. You can ping <discord-mention type="role" color="#70f0b4">Support</discord-mention> if you need help.
</discord-message>
```
which is far from actually good looking code.

If you want to retain your behaviour simple wrap the content of your `discord-message` in an extra `div` with the style change you applied here:
```html
<discord-message profile="maximillian">
	<div style="white-space: pre;">
		Hey, <discord-mention>Alyx Vargas</discord-mention> and <discord-mention>Dawn</discord-mention>. Welcome to our server!<br />Be
		sure to read through the <discord-mention type="channel">rules</discord-mention>. You can ping
		<discord-mention type="role" color="#70f0b4">Support</discord-mention>
		if you need help.
	</div>
</discord-message>
```

**Comment by DarkGuy10** [comment]
I see, I was using react component `<DiscordMessage>` and the `{children}` happens to be a dynamically provided string and not jsx. How do I fix that?
Is it possible to override `.discord-message-markup`?

**Comment by favna** [comment]
Just wrap {children} in a div where you read it as shown in my example above.

**Comment by DarkGuy10** [comment]
Ahhh, thanks, why didnt i think of that 
I'll go ahead and close this issue, and also the PR
