### ISSUE TITLE
request: Discord.js message objects to message embed

### ISSUE THREAD

**Issue by Galaxy-Coding** [skyra-project/discord-components#205]
**Is your feature request related to a problem? Please describe.**
It’s tedious to convert messages (especially when they are pulled directly from discord) to web components easily. It would be way faster and consistent if you just plug in an object and get the required html

**Describe the solution you'd like**

I think it would be cool if you could take a [discord.js message embed](https://discord.js.org/#/docs/discord.js/stable/class/Message) or an array of embeds and convert it to the html required to make the message components

**Comment by favna** [comment]
Sorry but this really it out of scope of this library. It would require quite a lot of parsing. I also think it would abusing props to suddenly dump a full JSON object into it. Not to mention that DiscordJS is a backend library (NodeJS) and this is a web library, so realistically they should never mix in the same codebase I think*

*unless you're attempting something akin https://github.com/favware/archangel in which case.. good luck. It's way more effort than it's worth.

**Comment by Galaxy-Coding** [comment]
@favna What is the relevance of https://github.com/favware/archangel to this topic? What is it?

**Comment by favna** [comment]
It is a private bot for the Populous Gaming server where we primarily use it to meme on 1 guy who has a lot of, as well call them, funny misadventures of him with tech. I made the bot to "quote" his messages while retaining a Discord-like style. Example:

![image](https://user-images.githubusercontent.com/4019718/153949495-87da7f25-812d-45b7-8c86-5cbfee074d62.png)

**Comment by favna** [comment]
I'm going to close this issue. As stated, it is out of scope of this library.
