### ISSUE TITLE
bug: wrong styling

### ISSUE THREAD

**Issue by DarkGuy10** [skyra-project/discord-components#215]
**Describe the bug**
A bunch of things are not styled like they should be.

1. **Embed author** (font-weight)
how it is: `{font-weight: 700}`
![image](https://user-images.githubusercontent.com/62807269/156931786-8134920a-d560-485c-8b61-1dabda41960d.png)
how it should be: `{font-weight: 600}`
![image](https://user-images.githubusercontent.com/62807269/156931867-cf7259bf-96c1-49e6-8d30-2f69d11364f3.png)

2. **Message author** (font-size, letter-spacing)
how it is: `{font-size:1.1em; letter-spacing: 0.5px}`
![image](https://user-images.githubusercontent.com/62807269/156931944-a672fb5e-0008-42fb-a927-b93d3dbccef4.png)
how it should be: `{font-size: 1rem;}` (discord uses default spacing)
![image](https://user-images.githubusercontent.com/62807269/156932178-ad3fe2fe-2317-4d02-b417-8dac45dd51fe.png)

3. **Embed footer** 
how it is:
![image](https://user-images.githubusercontent.com/62807269/156932295-1d9a414e-76cb-4e82-8b15-aed87fcb5c81.png)
how it should be:
![image](https://user-images.githubusercontent.com/62807269/156932313-9b288c0b-75c4-4468-a4c3-2625e96ead18.png)

4. **Message reply author**
how it is:
![image](https://user-images.githubusercontent.com/62807269/156932671-e017e003-9f42-442b-9986-59a89fc85747.png)
how it should be:
![image](https://user-images.githubusercontent.com/62807269/156932687-8cf95034-3491-49fb-9a3f-53ce2482e0b9.png)

Im using rule overrides with `!important` in my project to fix these for now<br>

**Comment by Tylertron1998** [comment]
I have some recommendations to help make your case a little better;

- firstly; out of context snippets do not help much. I'd recommend taking full screenshots of embeds to compare.
- secondly; it's difficult to compare when the content isn't exactly the same.
- and finally; some screenshots comparing both before and after versus a screenshot from an actual discord embed would be a huge help.

**Comment by DarkGuy10** [comment]
@Tylertron1998  Thanks for the suggestion! I will add full screenshots of embeds for all the things I pointed out above.

<table>
  <tr>
    <th align="center">from discord.com</th>
    <th align="center">using discord-components</th>
  </tr>
  <tr>
    <td align="center">
<img alt="" src="https://user-images.githubusercontent.com/62807269/156973053-8fcbfdf5-61ba-4883-87bc-ee2942e06cdc.png" alt=""></img>
</td>
<td align="center">
<img alt="" src="https://user-images.githubusercontent.com/62807269/156973132-49e35261-82fe-4141-a9dd-0c199e96a511.png" alt=""></img>
</td>
  </tr>
</table>

As you can see, the font-weight for the **embed-title**, **embed-author** and **embed-footer** are off

Another thing I've noticed  is that the fonts being used are not complete. Discord uses separate .woff files for font-weights 

Here's using discord-components with my overrides + added fonts 
<table>
  <tr>
    <th align="center">from discord.com</th>
    <th align="center">using my overrides + added fonts</th>
  </tr>
  <tr>
    <td align="center">
<img alt="" src="https://user-images.githubusercontent.com/62807269/156973053-8fcbfdf5-61ba-4883-87bc-ee2942e06cdc.png" alt=""></img>
</td>
<td align="center">
<img alt="" src="https://user-images.githubusercontent.com/62807269/156977565-3b646dcb-0b85-4612-8964-487377ef299c.png" alt=""></img>
</td>
  </tr>
</table>

**Comment by favna** [comment]
> using my overrides + added fonts

If you already have changes then feel free to make a PR

**Comment by favna** [comment]
I can fix the CDN assets, assuming that zip is the one to replace it with. 

I thought it was still correct but the fonts on the CDN *are* pre-rebranding.

**Comment by DarkGuy10** [comment]
Ahh that explains it, and yup, the zip is the one that replaces old assets.

I'll create a PR as soon as I fix the inconsistencies.
