### ISSUE TITLE
request: specific tags for text customization

### ISSUE THREAD

**Issue by HunteRoi** [skyra-project/discord-components#220]
**Is your feature request related to a problem? Please describe.**

I need to use text customizations like spoilers, quotes, code blocks and so on outside of embeds.

**Describe the solution you'd like**

Tags like `<DiscordBold>`, `<DiscordSpoiler>` or `<DiscordQuote>` for example.

**Describe alternatives you've considered**

Using my own CSS on span elements, but it feels wrong knowing I need to take into account the discord-message parents as well as the theme used.

**Additional context**

N.A.

**Comment by favna** [comment]
Do you happen to already have your own CSS? If so, can you make a PR? Or otherwise you can share that.

**Comment by HunteRoi** [comment]
My CSS is not fully styled like Discord and I have written it in the most easiest form so I am not sure it might be of good use. I mean anyone can set font-weight as bold...

**Comment by favna** [comment]
> I mean anyone can set font-weight as bold..

That is literally all that Discord does though. Wrap the text in `<strong>` tags and strong tags have `font-weight: 700`.

Anyway see commit above, they are added.

**Comment by favna** [comment]
Published as [v3.2.0](https://github.com/skyra-project/discord-components/releases/tag/v3.2.0)
