### ISSUE TITLE
request: support custom image component

### ISSUE THREAD

**Issue by TriForMine** [skyra-project/discord-components#251]
**Is your feature request related to a problem? Please describe.**

There is no way to pass a custom Image Component such as next/image, that would be really nice to have.
As, I'm trying to optimize my website as much as I can, and that's really blocking me.

**Describe the solution you'd like**

Having a way to pass custom Image component instead of just an image url on every component that can take an image.

**Comment by favna** [comment]
This will probably become more feasible after the Lit rewrite if I ever finish that because everything then extends HTMLElement internally but either before or until such time this PR is open for anyone to grab

**Comment by favna** [comment]
Added in [v4.0.0-alpha.20](https://github.com/skyra-project/discord-components/releases/tag/v4.0.0-alpha.20)
