### ISSUE TITLE
request: Support message timestamps

### ISSUE THREAD

**Issue by itohatweb** [skyra-project/discord-components#259]
**Describe the solution you'd like**
Discord has added [message timestamps](https://discord.com/developers/docs/reference#message-formatting-timestamp-styles) would be cool if that gets supported.

**Describe alternatives you've considered**
Display a normal date string.

**Comment by favna** [comment]
This is already a feature through the `discord-time` component. This library won't be parsing unix timestamps for you just like it also doesn't convert markdown to html and the likes.

**Comment by itohatweb** [comment]
Oo, didn't saw that one, thanks!
