### ISSUE TITLE
request: React custom Provider for discord options

### ISSUE THREAD

**Issue by wolffparkinson** [skyra-project/discord-components#274]
**Is your feature request related to a problem? Please describe.**

Managing profiles would be easier and more intuitive with React Providers

**Describe the solution you'd like**

```ts
<DiscordOptionsContext.Provider value={discordOptions}>
  <DiscordMessages>
    <DiscordMessage>...</DiscordMessage>
  </DiscordMessages>
  <DiscordMessages>
    <DiscordMessage>...</DiscordMessage>
  </DiscordMessages>
</DiscordOptionsContext.Provider>
```
Reference : [react-discord-message](https://github.com/Danktuary/react-discord-message) by Danktuary

**Describe alternatives you've considered**
Custom components, but that feels hacky.

**Additional context**

**Comment by favna** [comment]
This is not possible because the React code is fully autogenerated by Stencil (unlike the referenced package) so we cannot add custom code, especially not without jumping through major hoops of fire that would make the build process extremely complex.

**Comment by favna** [comment]
Closing this as per the answer above
