### ISSUE TITLE
bug: Components (React) do not work well with mutable data

### ISSUE THREAD

**Issue by Kyzegs** [skyra-project/discord-components#297]
**Describe the bug**

Changing state/data will break various components. I've tested this with a few components. You'll be able to mess around with the issues in the [CodeSandbox](https://codesandbox.io/s/discord-components-create-react-app-forked-j1qmor).

**To Reproduce**

[CodeSandbox](https://codesandbox.io/s/discord-components-create-react-app-forked-j1qmor)

**Expected behavior**

The components should keep working when state/data is mutated.

**Screenshots**

The field title is missing even though there is a value for it:

![Missing field title](https://user-images.githubusercontent.com/45851377/199865202-980b921d-7b6f-42cc-b7d5-1c738b300479.png)

**Additional context**

Error when mutating message content:

```
NotFoundError
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

**Comment by favna** [comment]
This is a known issue and will be resolved with the Lit Element rewrite, however I've been majorly lacking motivation to continue that branch.

**Comment by TheBv** [comment]
Any chance you could write down what the current status of the rewrite is/ what is missing?
I'd be willing to continue your work, but some rough outline on what needs to be done would be very much appreciated :)

**Comment by favna** [comment]
I can write a more detailed explanation after work, but in short the progress is in the rewrite branch and the components ported are: https://github.com/skyra-project/discord-components/tree/feat/rewrite-to-lit/packages/core/src/components

That said, I also don't quite recall to what state those components were done.

**Comment by favna** [comment]
This should be resolved in the new alpha version. A full release of that version will come in due time, can't give an exact time frame. I want to work through a few other issues and I still have to add list item components. You can use the alpha releases though. The README has been updated to provide templates for many different stacks.

**Comment by Kyzegs** [comment]
Thanks, thank you for the awesome work!

**Comment by Kyzegs** [comment]
I'll check it out. Thank you for the awesome work!

**Comment by favna** [comment]
I'm going to close this because OP hasn't replied anymore. I will assume that v4 has fixed this issue. If it hasn't, please reply again.
