### ISSUE TITLE
bug: Hydration errors

### ISSUE THREAD

**Issue by mrhappyma** [skyra-project/discord-components#301]
**Describe the bug**

Error popup and console logs
just look at the sandbox, i don't have time to write up a proper bug report
sorry

**To Reproduce**
(adjusted from my original code but still throws the same error)
[CodeSandbox](https://codesandbox.io/p/sandbox/busy-dew-d6vbq2)

**Comment by favna** [comment]
>  i don't have time to write up a proper bug report

And I don't have time to write up a proper response :) 

Server side rendering doesn't support webcomponents of any kind. Render them client side only.

**Comment by mrhappyma** [comment]
Thanks, with a bit of googling that helped 👍
