### ISSUE TITLE
request: Remove google fonts and self host the fonts

### ISSUE THREAD

**Issue by mezotv** [skyra-project/discord-components#308]
**Is your feature request related to a problem? Please describe.**

In Germany, using google fonts is against the dsgvo aka the privacy laws which forbids using google fonts on websites.

https://www.e-recht24.de/artikel/datenschutz/13052-datenschutz-und-google-fonts.htm

**Describe the solution you'd like**

Remove the Roboto font and replace it with a font face.

**Comment by favna** [comment]
This sounds like total nonsense lol. No way Germany is that dumb. 

Also the link is a dead one.

**Comment by castdrian** [comment]
cringe German djs user

**Comment by devramsean0** [comment]
surely this would make any site that uses adsense or google analytics (or any other google service) also in breach of GDPR?

**Comment by favna** [comment]
Released in v3.5.0

**Comment by mezotv** [comment]
Thanks!
