### ISSUE TITLE
request: ephemeral messages

### ISSUE THREAD

**Issue by River198** [skyra-project/discord-components#310]
Only you can see this message

**Is your feature request related to a problem? Please describe.**
No

"Only you can see this" message

**Comment by favna** [comment]
Already a feature: https://github.com/skyra-project/discord-components/tree/main/packages/core/src/components/discord-message#properties.

It's also included in the live demo that is linked in the README: 

[![Edit Button](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/discord-components-static-nhwkl)
