### ISSUE TITLE
request: Animated messages

### ISSUE THREAD

**Issue by daniellwdb** [skyra-project/discord-components#368]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

First of all, thank you for the library. It would be amazing to have animated (library specific?) messages. Think of deferred replies or just new messages popping up in a list.

### Desired solution

Either built-in support through properties or docs examples using a popular library like Framer would be amazing.

### Alternatives considered

There are no alternatives that I can think of.

**Comment by favna** [comment]
Going to close this. I gave it some more thought and I stick to it that this is up to the user to add themselves with their own animation library (or CSS) of choice. Especially with the Lit rewrite, currently available as 4.0.0 alphas, it is quite easy to add custom CSS and therefore animations to components.
