### ISSUE TITLE
request: AI option for AI bots

### ISSUE THREAD

**Issue by mezotv** [skyra-project/discord-components#369]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

The option for a bot to be an AI with the same badge used by the Clyde AI bot.

### Desired solution

Add a possible option to the Lit rewrite to mark a bot as AI. There is no rush, so this could be part of the Lit rewrite!

### Alternatives considered

None that come to mind at the moment. 

### Additional context

The color used for this badge would be #2dc770.

**Comment by favna** [comment]
Can we close this because Discord is killing Clyde? https://support.discord.com/hc/en-us/articles/13066317497239-Clyde-Discord-s-AI-Chatbot

**Comment by kyranet** [comment]
Yes, we can. No point in supporting something that will disappear forever in a few days.
