### ISSUE TITLE
request: Deleted message reply

### ISSUE THREAD

**Issue by Paillat-dev** [skyra-project/discord-components#371]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Show a reply to a deleted message, like this:
![image](https://github.com/skyra-project/discord-components/assets/75439456/5348a906-8d2d-43f5-80c2-ebbe768a11b1)

### Desired solution

Being able to set a reply element to, for example `deleted` and set it to show up as if the message replyed to was deleted.

### Alternatives considered

Just highliting the message and not showing it is a repl

**Comment by Paillat-dev** [comment]
Actually a pretty neat solution is a user with the arrow icon as profile pic, no name and `<discord-italic>Original message was deleted<discord-italic>` as content. A bit hacky but it works.

**Comment by favna** [comment]
This is available as of version [4.0.0-alpha.16](https://github.com/skyra-project/discord-components/releases/tag/v4.0.0-alpha.16) by adding a `deleted` property in `discord-reply`. A full release of 4.0.0 will be coming in the near future.
