### ISSUE TITLE
request: Discord Polls

### ISSUE THREAD

**Issue by GoldenAngel2** [skyra-project/discord-components#397]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Be able to create a Discord poll message: 

Poll Running: 
With multiple votes allowed: https://i.imgur.com/xIa45sd.png
With single vote allowed: https://i.imgur.com/ArqC1Gv.png

Poll End: 
Single vote: https://i.imgur.com/2ESlcs3.png
Multiple votes: https://i.imgur.com/Cp5tWSF.png
No votes: https://i.imgur.com/XyFLx9O.png

### Desired solution

Have something like 
- `<discord-poll>`
 > This would have something like: `question`, `expires`, `votes`
 - `<discord-poll-answer>` (this would be inside `<discord-poll>`)
 > This would have something like: `title` (or `answer`), `votes`, `emoji`
 
 > Unsure how to handle the poll end / answer winner(s)

### Alternatives considered

N/A

**Comment by favna** [comment]
I'm open to PRs for this. Quite a bit to add so it would be nice if someone could at least make a start at it.

**Comment by mezotv** [comment]
Maybe I will give this a try one day.

**Comment by eumarciel404** [comment]
I started doing this, I just don't know when it will be ready, so I'll send a pull request and leave it as drafted to make updates.

**Comment by eumarciel404** [comment]
I started doing this, I just don't know when it will be ready, so I'll send a pull request and leave it as drafted to make updates.

**Comment by eumarciel404** [comment]
![Screenshot_20241020-001259.png](https://github.com/user-attachments/assets/13e18154-084f-43df-8183-8d63311e4236)

**Comment by eumarciel404** [comment]
![image](https://github.com/user-attachments/assets/ab50d290-7e6f-49ae-a487-25a7a91f7375)

**Comment by favna** [comment]
Added in #492, released in [v4.0.0-alpha.36](https://github.com/skyra-project/discord-components/releases/tag/v4.0.0-alpha.36)
