### ISSUE TITLE
request: Message element without "user header"

### ISSUE THREAD

**Issue by nurdism** [skyra-project/discord-components#407]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

It would be nice to have the option to have a `discord-message` element that mimics a message sent by the same user in succession like so ![](https://i.imgur.com/AXLRY7a.png)

### Desired solution

Add a bool (I'm not sure about the name) that will toggle a user header.

### Alternatives considered

Right now, I am just looking to see if the last message was from the same user and then appending the message, but there are some inconsistencies between this lib and Discord. Specifically, the attachments and embeds.

**Comment by nurdism** [comment]
this would be very close to `compact-mode` just w/o a user title and the content on the same line

**Comment by favna** [comment]
Added in [v4.0.0-alpha.19](https://github.com/skyra-project/discord-components/releases/tag/v4.0.0-alpha.19), with the option being named `message-body-only` (or `messageBodyOnly` for React)
