### ISSUE TITLE
request: Add timestmap in "message body only" gutter

### ISSUE THREAD

**Issue by nurdism** [skyra-project/discord-components#418]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Would like the ability to add a timestamp to the "message body only" gutter like so

![](https://files.nurdism.dev/u/Pq0J6M.png)

### Desired solution

not sure if this would work but including `${computedTimestamp}` in the message body only like this

https://github.com/skyra-project/discord-components/blob/main/packages/core/src/components/discord-message/DiscordMessage.ts#L407 

```
${when(
	this.messageBodyOnly,
	() => html`<span class="discord-message-timestamp discord-message-body-only-indent">${computedTimestamp}</span>`,
	() => null
)}
```

### Alternatives considered

none

**Comment by favna** [comment]
Released in [alpha 22](https://github.com/skyra-project/discord-components/releases/tag/v4.0.0-alpha.22)
