### ISSUE TITLE
bug: mixing discord-bold/italic & discord-list-item causing spacing issues

### ISSUE THREAD

**Issue by nurdism** [skyra-project/discord-components#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Mixing discord-bold/italic causes stretched spacing inside discord-list-item

### Steps To Reproduce

```html
<discord-messages>
	<discord-message profile="favna">
		<discord-unordered-list>
			<discord-list-item>Normal</discord-list-item>
			<discord-list-item>Normal</discord-list-item>
			<discord-list-item>Normal</discord-list-item>
			<discord-list-item><discord-bold>Weird</discord-bold></discord-list-item>
			<discord-list-item><discord-italic>Weird</discord-italic></discord-list-item>
			<discord-list-item>Normal</discord-list-item>
		</discord-unordered-list>
	</discord-message>
</discord-messages>
```

### Expected behavior

spacing to be uniform

### Screenshots

![](https://files.nurdism.dev/u/ybn4a6.png)

### Additional context

This seems to be caused by [this css rule](https://github.com/skyra-project/discord-components/blob/fe237595f8af20a11d9d38e872ee1ee1af61b35f/packages/core/src/components/discord-list-item/DiscordListItem.ts#L11) specifically the `white-space: break-spaces;`

**Comment by favna** [comment]
Fixed in 4.0.0-alpha.29
