### ISSUE TITLE
request: Handle image errors and display fallback image

### ISSUE THREAD

**Issue by mezotv** [skyra-project/discord-components#452]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

The library should use its own image component that handles image errors and provides a fallback image either by the user or by the library itself (discord icon)

To prevent things like this

### Desired solution

Being able to provide a custom fallback image for when a url is expired or doesnt load properly.

### Alternatives considered

The library providing a hardcoded fallback image.

**Comment by favna** [comment]
You can use a NextImage already when using `DiscordImageAttachment`. That should handle all your cases far better than what this library can provide.

**Comment by mezotv** [comment]
Yea that is fair.
