### ISSUE TITLE
bug: in `discord-reply` the role color attribute is still `roleColor` instead of `role-color`

### ISSUE THREAD

**Issue by Paillat-dev** [skyra-project/discord-components#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

The html attribute to set the role color of a reply is `roleColor` instead of `role-color`.

### Steps To Reproduce

See this: https://stackblitz.com/edit/github-syurak?file=index.html

### Expected behavior

`role-color` to set the role color of a reply

### Screenshots

![image](https://github.com/user-attachments/assets/37bfa083-f0d2-44f4-87c3-6bf63a67281e)

**Comment by favna** [comment]
Thanks for catching this!

**Comment by favna** [comment]
released in [v4.0.0-alpha.36](https://github.com/skyra-project/discord-components/releases/tag/v4.0.0-alpha.36)
