### ISSUE TITLE
request: server tag

### ISSUE THREAD

**Issue by GoldenAngel2** [skyra-project/discord-components#88]
**Is your feature request related to a problem? Please describe.**
While there is a bot tag (`bot="true"`) there is none for a server.
> Could be used for displaying mockups of published messages

**Describe the solution you'd like**
Add `server="true"` to `<discord-message>`

**Describe alternatives you've considered/Additional context**
None

**Comment by Favna** [comment]
I have no idea what this would add for a message, could you describe it in more detail? I.e. show a screenshot of what kind of message you'd expect when setting this property. Or better yet, drop me an invite to a server where I can replicate a `server="true"` message, as I'll have to go into the inspector anyway to reproduce the message. My Discord tag is `Favna#0001`, if we don't share a server you can join https://join.skyra.pw.

**Comment by Favna** [comment]
nvm i got it. server crossposts.

**Comment by Favna** [comment]
This has been released in [version 2.1.0](https://github.com/skyra-project/discord-components/releases/tag/v2.1.0)
